config/routes.rb
Rails.application.routes.draw do
  
  resources :appointments do
	  resources :bookings
	end
  get 'startup/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]

  devise_for :users
  scope "/admin" do
  resources :users
end

  resources :users
  
  resources :topics do
    
  resources :reviews, except: [:show, :index]
  member do
      put "like" => "topics#upvote"
      put "unlike" => "topics#downvote"
end
end 

  root 'pages#index', as: 'home'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'news' => 'pages#news'
  get 'show' => 'topics#index'
  get 'pages/send_form' => 'pages#send_form'

  get 'new' => 'booking#new'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :reviews
	has_many :appointment
	has_many :resumes
	validates :title, presence: true,
						length: {minimum: 5}
	validates :body, presence: true,
						length: {minimum: 10}
	validates :image, presence: true


	mount_uploader :image, ImageUploader
	mount_uploader :video, VideoUploader
	mount_uploader :attachment, AttachmentUploader 

	def self.search(search)
        if search 
            where(["title LIKE ?","%#{search}%"])
        else
		all 
    end
end
end 

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    #before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
    before_action :find_topic, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:show, :index, :update, :destroy]
	before_action :set_topic, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	
	def index 
	  if params[:search].present?
	    @topics = Topic.search(params[:search]).paginate(:page => params[:page], :per_page => 5)
	    flash[:notice] = "No records found based on the search." if @topics.blank?
	  else
	    @topics = Topic.all.paginate(:page => params[:page], :per_page => 5) 
	    flash[:notice] = "No records found in Database." if @topics.blank?
	  end
	end

	def show
		@topic = Topic.find(params[:id])
		@reviews = Review.where(topic_id: @topic.id).order("created_at DESC")
		if @topic.reviews.blank?
		   @average_review = 0
		else
	    @average_review = @topic.reviews.average(:rating)
	end
	end 

	def new
		@topic = Topic.new
	end

	def create
		@topic = current_user.topics.build(topic_params)
		if (@topic.save)
			redirect_to @topic, notice: "This topic #{@topic.title} has been uploaded."
		else
			render 'new'
		end 
	end	

	def edit
		@topic = Topic.find(params[:id])
	end 

	def update
	    if @topic.update(topic_params)
			redirect_to topic_path(@topic), notice: "This topic #{@topic.title} has been updated."
		else
			render 'edit'
		end 
	end

	def destroy
		@topic = Topic.find(params[:id])
		@topic.destroy
		redirect_to topics_path, notice: 'Topic was successfully deleted.'
	end

	def upvote
	@topic.upvote_from current_user
	redirect_to topics_path(@topic)
	end 

	def downvote
	@topic.downvote_from current_user
	redirect_to topics_path(@topic)
	end 

	private 

	def topic_params
		params.require(:topic).permit(:topic_id, :title, :body, :date, :image, :remove_image, :video, :attachment)
	end

	def find_topic
	    @topic = Topic.find(params[:id])

	end

	def set_topic
		@topic = Topic.find(params[:id])
	end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1> Edit Topic </h1>
<%= form_for :topic, url: topic_path(@topic), method: :patch do |f| %>
	<% if @topic.errors.any? %>
		<% @topic.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	 <% end %>
	<p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
	<%= f.label :description %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<%= f.label :image %><br>
	<%= f.file_field :image %>
	<% if @topic.image %>
	  <%= image_tag @topic.image.url, class: "topic-show" %>
	  <%= f.check_box :remove_image %>
		Remove Image
	<% end %>

	<p>
	<%= f.label :video %><br>
    <%= f.file_field :video %>
    </p>

	<p>
	<%= f.label :date %><br>
	<%= f.date_select :date %>
	</p>

	<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>

	<%= link_to "Back", :back %>

<% end %>

app/views/topics/index.html.erb
<if !user_signed_in? %>

<br>
<%= link_to 'Download Topics', resumes_url, :class => 'btn btn-default' %>
<br>
<br>
<%= form_tag topics_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search], required: true %>
  <%= submit_tag "Search" %>   
<% end %>

<% @topics.each do |topic| %>
	<div class="topic">
	<h3><%= topic.title %></h3>
	<%= image_tag topic.image.url, class: "topic-show" if topic.image? %>
</div>

<!-- Voting like or dislike -->
<%= link_to like_topic_path(topic), class: "like", method: :put do %>
    <button type="button" class="btn btn-info" aria-label="Left Align">
    	<span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
    	<span class="badge"><%= topic.get_upvotes.size %></span>
    </button>
 <% end %>

 <%= link_to unlike_topic_path(topic), class: "unlike", method: :put do %>
    <button type="button" class="btn btn-info" aria-label="Right Align">
    	<span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
    	<span class="badge"><%= topic.get_downvotes.size %></span>
    </button>
 <% end %>
 <!-- End of voting -->
<br>
<br>
	<% if current_user && current_user.admin? %>
		<%= link_to "Edit", edit_topic_path(topic), :class => 'btn btn-default' %>
	<%= link_to "Destroy", topic, :class => 'btn btn-default', method: :delete, data: {confirm: 'Are you sure?'} %>
	<% end %>
	<%= link_to "Show", topic_path(topic), :class => 'btn btn-default' %>
<% end %>

<div>
	<%= will_paginate @topic, renderer: BootstrapPagination::Rails %>
</end>

<h2>Most Popular Posts</h2>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
<br>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="/topics/2" target="_blank">
          <img src="/assets/elder.jpg" alt="Lights" style="width:100%">
          <div class="caption">
            <p>How to use skype</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="/topics/6" target="_blank">
          <img src="/assets/fitbit.jpg" alt="Nature" style="width:100%">
          <div class="caption">
            <p>How does a fitbit benefit your health?</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-md-4">
      <div class="thumbnail">
        <a href="/topics/13" target="_blank">
          <img src="/assets/laptop.jpg" alt="Fjords" style="width:100%">
          <div class="caption">
            <p>How to set up emails</p>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<h1> Add Topics </h1>
<%= form_for @topic, :html => {:multipart => true} do |f| %>
	<% if @topic.errors.any? %>
		<% @topic.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	 <% end %>
	<p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
	<%= f.label :description %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<%= f.label :image %><br>
	<%= f.file_field :image %>
	<% if @topic.image %>
	  <%= image_tag @topic.image.url, class: "topic-show" %>
	  <%= f.check_box :remove_image %>
		Remove Image
	<% end %>

	<p>
	<%= f.label :video %><br>
    <%= f.file_field :video %>
    </p>

	<p>
	<div class="field">
	<%= f.label :date %><br>
	<%= f.date_select :date %>
	</p>
	</div>

	<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>

	<%= link_to "Back", :back %>
<% end %>

app/views/topics/show.html.erb
<div class="row">
	
<div class="col-md-5">

<!-- Image Show -->
<%= image_tag @topic.image.url, class: "topic-show" %>

</div>

<div class="col-md-6">
<br>
<br>
<h3><%= @topic.title %></h3>
<p>Average Rating </p> 
<div class="average-review-rating" data-score=<%= @average_review %>></div>
<span>Based on <%= @topic.reviews.count %> reviews </span>
<p> <%= simple_format( @topic.body) %> </p>
<p><%= @topic.date %></p>
<hr>
</div>
<br>
<br>


<br>
<br>

<div>
<%= link_to "Click here to write a review!", new_topic_review_path(@topic), :class => 'btn btn-custom' %>
</div>
<br>

<% if current_user && current_user.admin? %>
<%= link_to "Edit", edit_topic_path(@topic), :class => 'btn btn-custom' %>
<%= link_to "Delete", topic_path(@topic),
					method: :delete,
					data: {confirm: 'Are you sure?'},
					:class => 'btn btn-custom' %>
<% end %>
<br>
<!-- Video Show -->
<% if @topic.video.url %>
	<iframe width="800" height="500" src="<%= @topic.video.url %>" ></iframe>
	<br>
	<br> 
<% end %>

<br>
<br>

<div class="row">
	<div class="col-md-13">
	<div class="reviews">
<h3>Reviews</h3>
<% if @reviews.blank? %>
	          <h3>No reviews just yet, would you like to add the first?</h3>
	          <%= link_to "Write Review", new_topic_review_path(@topic), class: "btn btn-danger" %>
	        <% else %>
<!-- Where the reviews/ratings will go  -->
<%= render @topic.reviews %>
<% end %>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

<br>
<%= link_to 'Back', topics_path %>