config/routes.rb
Rails.application.routes.draw do
  
  resources :appointments do
	  resources :bookings
	end
  get 'startup/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]

  devise_for :users
  scope "/admin" do
  resources :users
end

  resources :users
  
  resources :topics do
    
  resources :reviews, except: [:show, :index]
  member do
      put "like" => "topics#upvote"
      put "unlike" => "topics#downvote"
end
end 

  root 'pages#index', as: 'home'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'news' => 'pages#news'
  get 'show' => 'topics#index'
  get 'pages/send_form' => 'pages#send_form'

  get 'new' => 'booking#new'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  belongs_to :user
  has_many :bookings
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @appointments = Appointment.where(user_id: current_user)
  end

  def new
    @appointment = current_user.appointments.build
  end

  def create
    @appointment = current_user.appointments.build(appointment_params)
    if @appointment.save
      name = @appointment.name
      redirect_to appointments_path
      flash[:notice] = "Appointment created"
    else
      render 'new'
      flash[:error] = "Unable to create appointment. Please try again"
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update appointment_params
    if @appointment.save
      flash[:notice] = "Your appointment was updated succesfully"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

    def appointment_params
      params.require(:appointment).permit(:name, :delete)
    end

end

app/views/appointments/_errors.html.erb
<% if @appointment.errors.any? %>
  <div class="errors">
    <h3>
      <%= pluralize(@appointment.errors.count, 'error') %>
      prohibited this appointment from being saved:
    </h3>
    <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>
  <%= render 'errors' %>
  <%= f.label 'Subject', 'Reason for appointment' %>
  <%= f.text_field 'name', placeholder: 'Short description'%>
  <%= f.submit 'Submit' %>
<br>
<br>
  <p>Please let us know the reason for booking the appointment, click "Submit" and add the time of your preffered choice!</p> 
<% end %>

app/views/appointments/edit.html.erb
<%= render 'form' %>

app/views/appointments/index.html.erb
<h3>appointments</h3>

<%= link_to "New Appointment", new_appointment_path,:class => 'btn btn-warning' %>

<% @appointments.each do |appointment| %>	
  <div class="appointment">
    <%= appointment.name %>    
    <%= link_to "Edit", edit_appointment_path(appointment),:class => 'btn btn-info' %>
	<%= link_to "Delete", appointment_path(appointment), data: { confirm: 'Are you sure?' }, method: :delete, :class => 'btn btn-info'  %>    
	<%= link_to "Add time", new_appointment_booking_path(appointment), :class => 'btn btn-info' %>  
    <%= link_to "Show my booking", appointment_bookings_path(appointment), :class => 'btn btn-info' %>
 </div>
<% end %>

app/views/appointments/new.html.erb
<%= render 'form' %>