config/routes.rb
Rails.application.routes.draw do
  
  resources :appointments do
	  resources :bookings
	end
  get 'startup/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]

  devise_for :users
  scope "/admin" do
  resources :users
end

  resources :users
  
  resources :topics do
    
  resources :reviews, except: [:show, :index]
  member do
      put "like" => "topics#upvote"
      put "unlike" => "topics#downvote"
end
end 

  root 'pages#index', as: 'home'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'news' => 'pages#news'
  get 'show' => 'topics#index'
  get 'pages/send_form' => 'pages#send_form'

  get 'new' => 'booking#new'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user! 
  before_action :find_topic
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @topic = Topic.find(params[:topic_id])
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.topic_id = @topic.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @topic, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    if @review.update(review_params)
      redirect_to topic_path(@topic), notice: 'Review was successfully updated.'
    else
      render 'edit'
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    redirect_to topic_path(@topic), notice: 'Review was successfully deleted.'
  end

  private
  def review_params
        params.require(:review).permit(:rating, :comment, :username)
      end

      def find_topic
        @topic = Topic.find(params[:topic_id])
      end

      def find_review
        @review = Review.find(params[:id])
      end
  end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for ([@topic, @topic.reviews.build]) do |f| %>
<div id="rating-form">
<label>Rating</label>
	</div>
<br>
<br>
<%= f.label :username %>
<%= f.text_field(:username) %>
<%= f.input :comment %>
<%= f.button :submit %> 

<% end %>

<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/_review.html.erb
<div class="review">

<!-- Display for reviews -->
<p><strong><%= review.username %></strong></p> 
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"><%= review.comment %></p>

<!-- Only if user signed in, display edit and delete -->
<% if user_signed_in? %>
<% if review.user_id == current_user.id %>

<%= link_to "Edit", edit_topic_review_path(review.topic, review) %>
<%= link_to "Delete", topic_review_path(review.topic, review), method: :delete, data: { confirm: "Are you sure?"} %>

<% end %>

<% end %>

</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@topic, @review]) do |f| %>
<div id="rating-form">
<label>Rating</label>
	</div>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %> 

<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/new.html.erb
<h1>New Reviews</h1>

<%= render 'form' %>