config/routes.rb
Rails.application.routes.draw do
  
  resources :appointments do
	  resources :bookings
	end
  get 'startup/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]

  devise_for :users
  scope "/admin" do
  resources :users
end

  resources :users
  
  resources :topics do
    
  resources :reviews, except: [:show, :index]
  member do
      put "like" => "topics#upvote"
      put "unlike" => "topics#downvote"
end
end 

  root 'pages#index', as: 'home'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'news' => 'pages#news'
  get 'show' => 'topics#index'
  get 'pages/send_form' => 'pages#send_form'

  get 'new' => 'booking#new'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<nav>
	<div class="socialmedia">
		<footer class="bg-black small text-center text-white-50">
	    <div class="container">
	      Copyright &copy; TechMadeEasy 2019
	    </div>
	  </footer>
</nav>
</footer>

app/views/layouts/_header.html.erb
     <nav>
    <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home", home_path, :class => 'btn btn-custom' %></li>
        <li><%= link_to "About Us", about_path, :class => 'btn btn-custom' %></li>
        <li><%= link_to "Topics", topics_path, :class => 'btn btn-custom' %> </li>
        <li><%= link_to "News", news_path, :class => 'btn btn-custom' %></li>
        <li><%= link_to "Contact", contact_path, :class => 'btn btn-custom' %></li><br>
        <% if user_signed_in? %>
        <li>Logged in as <strong><%= current_user.email %></strong></li>
        <% end %>
        <br>
    </ul>

    <ul class="nav navbar-nav navbar-right">
    <%if current_user && current_user.admin? %>
    <li><%= link_to "Create Topic", new_topic_path, :class => 'btn btn-custom' %></li>
    <li><%= link_to "Manage Users", admin_dashboard_path, :class => 'btn btn-custom' %></li>
    <% end %>

    <% if user_signed_in? %>

    <li><%= link_to "Appointments", appointments_path, :class => 'btn btn-custom' %></li>

    <li><%= link_to "Edit Profile", edit_user_registration_path, :class => 'btn btn-custom' %></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'btn btn-custom' %></li>
       <% else %>
    <li><%= link_to "Register", new_user_registration_path, :class => 'btn btn-custom' %></li>
    <li><%= link_to "Sign In", new_user_session_path, :class => 'btn btn-custom' %></li>
    <% end %>
    </ul>

</nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<! [endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechMadeEasy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-casual.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">


  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>

   <div class="address-bar">Tech Made Easy!</div>
  <div class="slogan-bar">Learn how to use the latest technology with just a simple click!</div>

  <!-- Resizing font -->
  <div id="acess-icons" class="" style="display: block; font-size: 16px;">
            <div class="acess-icon" style="font-size: 16px;"><img id="increaseFont" title="Increase Font" src="assets/fontsma40.png" class="" style="font-size: 16px;"></div>
            <div class="acess-icon" style="font-size: 16px;"><img id="decreaseFont" title="Decrease Font" src="assets/fontsme40.png" class="" style="font-size: 16px;"></div>
        </div>
  <br>
  <div class="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>